// Code generated by mockery v2.10.1. DO NOT EDIT.

package mocks

import (
	errors "auth/internal/errors"
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "auth/internal/dao/mongodao/models"
)

// MongoDAO is an autogenerated mock type for the MongoDAO type
type MongoDAO struct {
	mock.Mock
}

// AddUser provides a mock function with given fields: ctx, user
func (_m *MongoDAO) AddUser(ctx context.Context, user model.User) *errors.ServerError {
	ret := _m.Called(ctx, user)

	var r0 *errors.ServerError
	if rf, ok := ret.Get(0).(func(context.Context, model.User) *errors.ServerError); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.ServerError)
		}
	}

	return r0
}

// FindUserByEmail provides a mock function with given fields: ctx, email
func (_m *MongoDAO) FindUserByEmail(ctx context.Context, email string) (model.User, *errors.ServerError) {
	ret := _m.Called(ctx, email)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 *errors.ServerError
	if rf, ok := ret.Get(1).(func(context.Context, string) *errors.ServerError); ok {
		r1 = rf(ctx, email)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.ServerError)
		}
	}

	return r0, r1
}
