// Code generated by go-swagger; DO NOT EDIT.

package bookkeeping_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBookkeepingHandlerFunc turns a function with the right signature into a get bookkeeping handler
type GetBookkeepingHandlerFunc func(GetBookkeepingParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBookkeepingHandlerFunc) Handle(params GetBookkeepingParams) middleware.Responder {
	return fn(params)
}

// GetBookkeepingHandler interface for that can handle valid get bookkeeping params
type GetBookkeepingHandler interface {
	Handle(GetBookkeepingParams) middleware.Responder
}

// NewGetBookkeeping creates a new http.Handler for the get bookkeeping operation
func NewGetBookkeeping(ctx *middleware.Context, handler GetBookkeepingHandler) *GetBookkeeping {
	return &GetBookkeeping{Context: ctx, Handler: handler}
}

/* GetBookkeeping swagger:route GET /bookkeeping/ bookkeeping-service getBookkeeping

GetBookkeeping get bookkeeping API

*/
type GetBookkeeping struct {
	Context *middleware.Context
	Handler GetBookkeepingHandler
}

func (o *GetBookkeeping) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBookkeepingParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
