// Code generated by go-swagger; DO NOT EDIT.

package bookkeeping_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dhi13man/healthcare-app/models"
)

// GetBookkeepingOKCode is the HTTP code returned for type GetBookkeepingOK
const GetBookkeepingOKCode int = 200

/*GetBookkeepingOK The bookkeeping-service endpoint

swagger:response getBookkeepingOK
*/
type GetBookkeepingOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Medicine `json:"body,omitempty"`
}

// NewGetBookkeepingOK creates GetBookkeepingOK with default headers values
func NewGetBookkeepingOK() *GetBookkeepingOK {

	return &GetBookkeepingOK{}
}

// WithPayload adds the payload to the get bookkeeping o k response
func (o *GetBookkeepingOK) WithPayload(payload []*models.Medicine) *GetBookkeepingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bookkeeping o k response
func (o *GetBookkeepingOK) SetPayload(payload []*models.Medicine) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBookkeepingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Medicine, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetBookkeepingDefault generic error response

swagger:response getBookkeepingDefault
*/
type GetBookkeepingDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBookkeepingDefault creates GetBookkeepingDefault with default headers values
func NewGetBookkeepingDefault(code int) *GetBookkeepingDefault {
	if code <= 0 {
		code = 500
	}

	return &GetBookkeepingDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get bookkeeping default response
func (o *GetBookkeepingDefault) WithStatusCode(code int) *GetBookkeepingDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get bookkeeping default response
func (o *GetBookkeepingDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get bookkeeping default response
func (o *GetBookkeepingDefault) WithPayload(payload *models.Error) *GetBookkeepingDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bookkeeping default response
func (o *GetBookkeepingDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBookkeepingDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
