// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChargeServiceClient is the client API for ChargeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChargeServiceClient interface {
	Charge(ctx context.Context, in *ChargeRequest, opts ...grpc.CallOption) (*ChargeResponse, error)
}

type chargeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChargeServiceClient(cc grpc.ClientConnInterface) ChargeServiceClient {
	return &chargeServiceClient{cc}
}

func (c *chargeServiceClient) Charge(ctx context.Context, in *ChargeRequest, opts ...grpc.CallOption) (*ChargeResponse, error) {
	out := new(ChargeResponse)
	err := c.cc.Invoke(ctx, "/protobuf.ChargeService/Charge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChargeServiceServer is the server API for ChargeService service.
// All implementations must embed UnimplementedChargeServiceServer
// for forward compatibility
type ChargeServiceServer interface {
	Charge(context.Context, *ChargeRequest) (*ChargeResponse, error)
	mustEmbedUnimplementedChargeServiceServer()
}

// UnimplementedChargeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChargeServiceServer struct {
}

func (UnimplementedChargeServiceServer) Charge(context.Context, *ChargeRequest) (*ChargeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Charge not implemented")
}
func (UnimplementedChargeServiceServer) mustEmbedUnimplementedChargeServiceServer() {}

// UnsafeChargeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChargeServiceServer will
// result in compilation errors.
type UnsafeChargeServiceServer interface {
	mustEmbedUnimplementedChargeServiceServer()
}

func RegisterChargeServiceServer(s grpc.ServiceRegistrar, srv ChargeServiceServer) {
	s.RegisterService(&ChargeService_ServiceDesc, srv)
}

func _ChargeService_Charge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChargeServiceServer).Charge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ChargeService/Charge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChargeServiceServer).Charge(ctx, req.(*ChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChargeService_ServiceDesc is the grpc.ServiceDesc for ChargeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChargeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.ChargeService",
	HandlerType: (*ChargeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Charge",
			Handler:    _ChargeService_Charge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/charge.proto",
}
