// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Taranjeet Singh",
            "email": "singhtaran1515@gmail.com"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/train/add": {
            "post": {
                "description": "Add a Train",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Add a Train.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "Name",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Train Number",
                        "name": "TrainNumber",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Source",
                        "name": "Source",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Destination",
                        "name": "Destination",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Number Of Seats",
                        "name": "NumberOfSeats",
                        "required": true
                    },
                    {
                        "type": "number[]",
                        "description": "Reserved Seats",
                        "name": "ReservedSeats",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            },
        },
        "/train/{trainId}": {
            "get": {
                "security": [
                    {
                        "Bearer Token": []
                    }
                ],
                "description": "Get a particular Train.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Get a particular Train",
                "responses": {
                    "200": {
                        "description": "OK",
                    },
                    "500": {
                        "description": "Internal Server Error",
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer Token": []
                    }
                ],
                "description": "Edit a particular Train.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Edit a particular Train",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "Name",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Train Number",
                        "name": "TrainNumber",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Source",
                        "name": "Source",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Destination",
                        "name": "Destination",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Number Of Seats",
                        "name": "NumberOfSeats",
                        "required": true
                    },
                    {
                        "type": "number[]",
                        "description": "Reserved Seats",
                        "name": "ReservedSeats",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                    },
                    "500": {
                        "description": "Internal Server Error",
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer Token": []
                    }
                ],
                "description": "Delete a particular traon.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Delete a particular Train",
                "responses": {
                    "200": {
                        "description": "OK",
                    },
                    "500": {
                        "description": "Internal Server Error",
                    }
                }
            },
        },
        "/train/": {
            "get": {
                "security": [
                    {
                        "Bearer Token": []
                    }
                ],
                "description": "Get all train.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Get all train",
                "responses": {
                    "200": {
                        "description": "OK",
                    },
                    "500": {
                        "description": "Internal Server Error",
                    }
                }
            },
        },
        "/train/search": {
            "get": {
                "security": [
                    {
                        "Bearer Token": []
                    }
                ],
                "description": "Search a train.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Search a train",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source",
                        "name": "Source",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Destination",
                        "name": "Destination",
                        "required": true
                    },
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                    },
                    "500": {
                        "description": "Internal Server Error",
                    }
                }
            },
        },
        "/train/update-seats": {
            "get": {
                "security": [
                    {
                        "Bearer Token": []
                    }
                ],
                "description": "Update seats.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Update seats",
                "responses": {
                    "200": {
                        "description": "OK",
                    },
                    "500": {
                        "description": "Internal Server Error",
                    }
                }
            },
        }

    },
    "definitions": {
        "trainModel.Train": {
            "type": "object",
            "required": [
                "category",
                "price",
                "seller",
                "title"
            ],
            "properties": {
                "Name": {
                    "type": "string"
                },
                "TrainNumber": {
                    "type": "integer"
                },
                "Source": {
                    "type": "string"
                },
                "Destination": {
                    "type": "string"
                },
                "NumberOfSeats": {
                    "type": "integer"
                },
                "ReservedSeats": {
                    "type": "integer[]"
                },
            }
        }
    },
    
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8001",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Train Reservation System - Train Service",
	Description:      "Train Microservice",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
