// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Swastik Sahoo",
            "email": "swastiksahoo22@gmail.com"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/train/delete/{train_number}": {
            "delete": {
                "security": [
                    {
                        "Bearer Token": []
                    }
                ],
                "description": "To remove a particular train.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Delete Train",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Train Number",
                        "name": "train_number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "/train/get/{train_number}": {
            "get": {
                "security": [
                    {
                        "Bearer Token": []
                    }
                ],
                "description": "To get train details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Get Train",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Train Number",
                        "name": "train_number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Train"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "/train/getall": {
            "get": {
                "security": [
                    {
                        "Bearer Token": []
                    }
                ],
                "description": "To get every train detail.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Get all Train details",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Train"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "/train/register": {
            "post": {
                "security": [
                    {
                        "Bearer Token": []
                    }
                ],
                "description": "To register a new train for the app.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Register Train",
                "parameters": [
                    {
                        "description": "Train structure",
                        "name": "train",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Train"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "number"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "/train/update/{train_number}": {
            "patch": {
                "security": [
                    {
                        "Bearer Token": []
                    }
                ],
                "description": "To update train details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Update Train",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Train Number",
                        "name": "train_number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Train": {
            "type": "object",
            "properties": {
                "destination": {
                    "type": "string"
                },
                "seats_available": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "source": {
                    "type": "string"
                },
                "total_seats": {
                    "type": "integer"
                },
                "train_name": {
                    "type": "string"
                },
                "train_number": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer Token": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Train Module",
	Description:      "This microservice is for train module.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
