// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/doctor": {
            "get": {
                "description": "fetch all doctor",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Doctor"
                ],
                "summary": "fetch all  doctor",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Doctor"
                            }
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            },
            "post": {
                "description": "create doctor",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Doctor"
                ],
                "summary": "create doctor",
                "parameters": [
                    {
                        "description": "doctor info",
                        "name": "doctor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.DoctorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/doctor/{_id}": {
            "patch": {
                "description": "Update doctor",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Doctor"
                ],
                "summary": "Update doctor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "doctor info",
                        "name": "doctor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.DoctorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/user/{_id}": {
            "delete": {
                "tags": [
                    "Doctor"
                ],
                "summary": "Delete doctor by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.DoctorRequest": {
            "description": "Doctor Request",
            "type": "object",
            "required": [
                "name",
                "qualification"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "qualification": {
                    "type": "string"
                }
            }
        },
        "models.Doctor": {
            "description": "Doctor",
            "type": "object",
            "required": [
                "name",
                "qualification"
            ],
            "properties": {
                "_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qualification": {
                    "type": "string"
                },
                "updated_on": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7451",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Doctor Service",
	Description:      "This is doctor crud service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
