// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: pb/expert.proto

package gRPC

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ratingstruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rating int32  `protobuf:"varint,1,opt,name=rating,proto3" json:"rating,omitempty"`
	Review string `protobuf:"bytes,2,opt,name=review,proto3" json:"review,omitempty"`
}

func (x *Ratingstruct) Reset() {
	*x = Ratingstruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_expert_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ratingstruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ratingstruct) ProtoMessage() {}

func (x *Ratingstruct) ProtoReflect() protoreflect.Message {
	mi := &file_pb_expert_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ratingstruct.ProtoReflect.Descriptor instead.
func (*Ratingstruct) Descriptor() ([]byte, []int) {
	return file_pb_expert_proto_rawDescGZIP(), []int{0}
}

func (x *Ratingstruct) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Ratingstruct) GetReview() string {
	if x != nil {
		return x.Review
	}
	return ""
}

type Expert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username     string          `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Skill        string          `protobuf:"bytes,3,opt,name=skill,proto3" json:"skill,omitempty"`
	Email        string          `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Isavailable  bool            `protobuf:"varint,5,opt,name=isavailable,proto3" json:"isavailable,omitempty"`
	Served       int32           `protobuf:"varint,6,opt,name=served,proto3" json:"served,omitempty"`
	Rating       float32         `protobuf:"fixed32,7,opt,name=rating,proto3" json:"rating,omitempty"`
	Location     int64           `protobuf:"varint,8,opt,name=location,proto3" json:"location,omitempty"`
	Ratingstruct []*Ratingstruct `protobuf:"bytes,9,rep,name=ratingstruct,proto3" json:"ratingstruct,omitempty"` //   string reviews=9;
}

func (x *Expert) Reset() {
	*x = Expert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_expert_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expert) ProtoMessage() {}

func (x *Expert) ProtoReflect() protoreflect.Message {
	mi := &file_pb_expert_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expert.ProtoReflect.Descriptor instead.
func (*Expert) Descriptor() ([]byte, []int) {
	return file_pb_expert_proto_rawDescGZIP(), []int{1}
}

func (x *Expert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Expert) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Expert) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *Expert) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Expert) GetIsavailable() bool {
	if x != nil {
		return x.Isavailable
	}
	return false
}

func (x *Expert) GetServed() int32 {
	if x != nil {
		return x.Served
	}
	return 0
}

func (x *Expert) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Expert) GetLocation() int64 {
	if x != nil {
		return x.Location
	}
	return 0
}

func (x *Expert) GetRatingstruct() []*Ratingstruct {
	if x != nil {
		return x.Ratingstruct
	}
	return nil
}

type ExpertId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ExpertId) Reset() {
	*x = ExpertId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_expert_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpertId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpertId) ProtoMessage() {}

func (x *ExpertId) ProtoReflect() protoreflect.Message {
	mi := &file_pb_expert_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpertId.ProtoReflect.Descriptor instead.
func (*ExpertId) Descriptor() ([]byte, []int) {
	return file_pb_expert_proto_rawDescGZIP(), []int{2}
}

func (x *ExpertId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ExpertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expertid *ExpertId `protobuf:"bytes,1,opt,name=expertid,proto3" json:"expertid,omitempty"`
}

func (x *ExpertRequest) Reset() {
	*x = ExpertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_expert_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpertRequest) ProtoMessage() {}

func (x *ExpertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_expert_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpertRequest.ProtoReflect.Descriptor instead.
func (*ExpertRequest) Descriptor() ([]byte, []int) {
	return file_pb_expert_proto_rawDescGZIP(), []int{3}
}

func (x *ExpertRequest) GetExpertid() *ExpertId {
	if x != nil {
		return x.Expertid
	}
	return nil
}

type ExpertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expert *Expert `protobuf:"bytes,1,opt,name=expert,proto3" json:"expert,omitempty"`
}

func (x *ExpertResponse) Reset() {
	*x = ExpertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_expert_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpertResponse) ProtoMessage() {}

func (x *ExpertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_expert_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpertResponse.ProtoReflect.Descriptor instead.
func (*ExpertResponse) Descriptor() ([]byte, []int) {
	return file_pb_expert_proto_rawDescGZIP(), []int{4}
}

func (x *ExpertResponse) GetExpert() *Expert {
	if x != nil {
		return x.Expert
	}
	return nil
}

var File_pb_expert_proto protoreflect.FileDescriptor

var file_pb_expert_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x32, 0x22, 0x3e, 0x0a, 0x0c, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x22, 0x84, 0x02, 0x0a, 0x06, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69,
	0x73, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x0c, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x32, 0x2e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0c,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x22, 0x1a, 0x0a, 0x08,
	0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x65,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x08, 0x65, 0x78, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x32,
	0x2e, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x49, 0x64, 0x52, 0x08, 0x65, 0x78, 0x70, 0x65, 0x72,
	0x74, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x0e, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x32, 0x2e, 0x45, 0x78, 0x70, 0x65, 0x72,
	0x74, 0x52, 0x06, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x32, 0x43, 0x0a, 0x07, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x11, 0x2e, 0x70, 0x32, 0x2e, 0x45, 0x78, 0x70, 0x65, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x32, 0x2e, 0x45, 0x78,
	0x70, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05,
	0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_expert_proto_rawDescOnce sync.Once
	file_pb_expert_proto_rawDescData = file_pb_expert_proto_rawDesc
)

func file_pb_expert_proto_rawDescGZIP() []byte {
	file_pb_expert_proto_rawDescOnce.Do(func() {
		file_pb_expert_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_expert_proto_rawDescData)
	})
	return file_pb_expert_proto_rawDescData
}

var file_pb_expert_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_expert_proto_goTypes = []interface{}{
	(*Ratingstruct)(nil),   // 0: p2.Ratingstruct
	(*Expert)(nil),         // 1: p2.Expert
	(*ExpertId)(nil),       // 2: p2.ExpertId
	(*ExpertRequest)(nil),  // 3: p2.ExpertRequest
	(*ExpertResponse)(nil), // 4: p2.ExpertResponse
}
var file_pb_expert_proto_depIdxs = []int32{
	0, // 0: p2.Expert.ratingstruct:type_name -> p2.Ratingstruct
	2, // 1: p2.ExpertRequest.expertid:type_name -> p2.ExpertId
	1, // 2: p2.ExpertResponse.expert:type_name -> p2.Expert
	3, // 3: p2.Service.ExpertService:input_type -> p2.ExpertRequest
	4, // 4: p2.Service.ExpertService:output_type -> p2.ExpertResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_expert_proto_init() }
func file_pb_expert_proto_init() {
	if File_pb_expert_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_expert_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ratingstruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_expert_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_expert_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpertId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_expert_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_expert_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_expert_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_expert_proto_goTypes,
		DependencyIndexes: file_pb_expert_proto_depIdxs,
		MessageInfos:      file_pb_expert_proto_msgTypes,
	}.Build()
	File_pb_expert_proto = out.File
	file_pb_expert_proto_rawDesc = nil
	file_pb_expert_proto_goTypes = nil
	file_pb_expert_proto_depIdxs = nil
}
