// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	domain "order/domain"
	errs "order/utils/errs"

	mock "github.com/stretchr/testify/mock"
)

// OrderRepositoryDB is an autogenerated mock type for the OrderRepositoryDB type
type OrderRepositoryDB struct {
	mock.Mock
}

// FetchOrderById provides a mock function with given fields: _a0
func (_m *OrderRepositoryDB) FetchOrderById(_a0 string) (*domain.Order, *errs.AppError) {
	ret := _m.Called(_a0)

	var r0 *domain.Order
	if rf, ok := ret.Get(0).(func(string) *domain.Order); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(string) *errs.AppError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0
func (_m *OrderRepositoryDB) Save(_a0 domain.Order) (*domain.Order, *errs.AppError) {
	ret := _m.Called(_a0)

	var r0 *domain.Order
	if rf, ok := ret.Get(0).(func(domain.Order) *domain.Order); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	var r1 *errs.AppError
	if rf, ok := ret.Get(1).(func(domain.Order) *errs.AppError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.AppError)
		}
	}

	return r0, r1
}
