// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: protobuf/availticket.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvailTicketResponse_MessageType int32

const (
	AvailTicketResponse_SUCESS     AvailTicketResponse_MessageType = 0
	AvailTicketResponse_INVALID    AvailTicketResponse_MessageType = 1
	AvailTicketResponse_NOCAPACITY AvailTicketResponse_MessageType = 2
)

// Enum value maps for AvailTicketResponse_MessageType.
var (
	AvailTicketResponse_MessageType_name = map[int32]string{
		0: "SUCESS",
		1: "INVALID",
		2: "NOCAPACITY",
	}
	AvailTicketResponse_MessageType_value = map[string]int32{
		"SUCESS":     0,
		"INVALID":    1,
		"NOCAPACITY": 2,
	}
)

func (x AvailTicketResponse_MessageType) Enum() *AvailTicketResponse_MessageType {
	p := new(AvailTicketResponse_MessageType)
	*p = x
	return p
}

func (x AvailTicketResponse_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvailTicketResponse_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_availticket_proto_enumTypes[0].Descriptor()
}

func (AvailTicketResponse_MessageType) Type() protoreflect.EnumType {
	return &file_protobuf_availticket_proto_enumTypes[0]
}

func (x AvailTicketResponse_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvailTicketResponse_MessageType.Descriptor instead.
func (AvailTicketResponse_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_availticket_proto_rawDescGZIP(), []int{1, 0}
}

type AvailTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainId      string `protobuf:"bytes,1,opt,name=trainId,proto3" json:"trainId,omitempty"`
	NumOfTickets uint32 `protobuf:"varint,2,opt,name=numOfTickets,proto3" json:"numOfTickets,omitempty"`
}

func (x *AvailTicketRequest) Reset() {
	*x = AvailTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_availticket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailTicketRequest) ProtoMessage() {}

func (x *AvailTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_availticket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailTicketRequest.ProtoReflect.Descriptor instead.
func (*AvailTicketRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_availticket_proto_rawDescGZIP(), []int{0}
}

func (x *AvailTicketRequest) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

func (x *AvailTicketRequest) GetNumOfTickets() uint32 {
	if x != nil {
		return x.NumOfTickets
	}
	return 0
}

type AvailTicketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Station1      string                          `protobuf:"bytes,1,opt,name=station1,proto3" json:"station1,omitempty"`
	Station2      string                          `protobuf:"bytes,2,opt,name=station2,proto3" json:"station2,omitempty"`
	ArrivalTime   string                          `protobuf:"bytes,3,opt,name=arrivalTime,proto3" json:"arrivalTime,omitempty"`
	DepartureTime string                          `protobuf:"bytes,4,opt,name=departureTime,proto3" json:"departureTime,omitempty"`
	Message       AvailTicketResponse_MessageType `protobuf:"varint,5,opt,name=message,proto3,enum=protobuf.AvailTicketResponse_MessageType" json:"message,omitempty"`
}

func (x *AvailTicketResponse) Reset() {
	*x = AvailTicketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_availticket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailTicketResponse) ProtoMessage() {}

func (x *AvailTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_availticket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailTicketResponse.ProtoReflect.Descriptor instead.
func (*AvailTicketResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_availticket_proto_rawDescGZIP(), []int{1}
}

func (x *AvailTicketResponse) GetStation1() string {
	if x != nil {
		return x.Station1
	}
	return ""
}

func (x *AvailTicketResponse) GetStation2() string {
	if x != nil {
		return x.Station2
	}
	return ""
}

func (x *AvailTicketResponse) GetArrivalTime() string {
	if x != nil {
		return x.ArrivalTime
	}
	return ""
}

func (x *AvailTicketResponse) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

func (x *AvailTicketResponse) GetMessage() AvailTicketResponse_MessageType {
	if x != nil {
		return x.Message
	}
	return AvailTicketResponse_SUCESS
}

var File_protobuf_availticket_proto protoreflect.FileDescriptor

var file_protobuf_availticket_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x52, 0x0a, 0x12, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x6e, 0x75,
	0x6d, 0x4f, 0x66, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x22, 0x92, 0x02, 0x0a, 0x13, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x31, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x72,
	0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x43, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x36, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x55, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x12,
	0x0e, 0x0a, 0x0a, 0x4e, 0x4f, 0x43, 0x41, 0x50, 0x41, 0x43, 0x49, 0x54, 0x59, 0x10, 0x02, 0x32,
	0x6c, 0x0a, 0x12, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protobuf_availticket_proto_rawDescOnce sync.Once
	file_protobuf_availticket_proto_rawDescData = file_protobuf_availticket_proto_rawDesc
)

func file_protobuf_availticket_proto_rawDescGZIP() []byte {
	file_protobuf_availticket_proto_rawDescOnce.Do(func() {
		file_protobuf_availticket_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_availticket_proto_rawDescData)
	})
	return file_protobuf_availticket_proto_rawDescData
}

var file_protobuf_availticket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_availticket_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_availticket_proto_goTypes = []interface{}{
	(AvailTicketResponse_MessageType)(0), // 0: protobuf.AvailTicketResponse.MessageType
	(*AvailTicketRequest)(nil),           // 1: protobuf.AvailTicketRequest
	(*AvailTicketResponse)(nil),          // 2: protobuf.AvailTicketResponse
}
var file_protobuf_availticket_proto_depIdxs = []int32{
	0, // 0: protobuf.AvailTicketResponse.message:type_name -> protobuf.AvailTicketResponse.MessageType
	1, // 1: protobuf.AvailTicketService.GetTicketConfirmation:input_type -> protobuf.AvailTicketRequest
	2, // 2: protobuf.AvailTicketService.GetTicketConfirmation:output_type -> protobuf.AvailTicketResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_availticket_proto_init() }
func file_protobuf_availticket_proto_init() {
	if File_protobuf_availticket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_availticket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_availticket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailTicketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_availticket_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_availticket_proto_goTypes,
		DependencyIndexes: file_protobuf_availticket_proto_depIdxs,
		EnumInfos:         file_protobuf_availticket_proto_enumTypes,
		MessageInfos:      file_protobuf_availticket_proto_msgTypes,
	}.Build()
	File_protobuf_availticket_proto = out.File
	file_protobuf_availticket_proto_rawDesc = nil
	file_protobuf_availticket_proto_goTypes = nil
	file_protobuf_availticket_proto_depIdxs = nil
}
