// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Healthcare App
//
//  A Simple Healthcare app built to illustrate the concepts learnt during Swigggy i++ Training.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/github.com/dhi13man/healthcare-app.v1+json
//
//  Produces:
//    - application/github.com/dhi13man/healthcare-app.v1+json
//
// swagger:meta
package restapi
